export interface TimePredictionInputFeatures{

    sense : number;
    starting_bpm  : number;
    ending_bpm     : number;
    max_bpm         : number;
    median_bpm       : number;
    mean_bpm           : number;
    min_bpm           : number;
    delta_bpm           : number;
    previous_mean_delta_bpm  : number;
    variance_bpm             : number;
    std_bpm                  : number;
    previous_cronos_mean     : number;
    previous_cronos_std      : number;
    previous_cronos_variance : number;
    previous_cronos_worst   : number;
    previous_cronos_best     : number;
    recovery_time : number;
    phase                    : number;
    total_previous_sprints   : number;
    same_half_previous_sprints : number;
    previous_max_bpm_mean   : number;
    previous_max_bpm_std     : number;
    previous_max_bpm_variance: number;
    previous_max_bpm_min     : number;
    previous_max_bpm_max     : number;
    previous_min_bpm_mean    : number;
    previous_min_bpm_std     : number;
    previous_min_bpm_variance: number;
    previous_min_bpm_min     : number;
    previous_min_bpm_max     : number;
    previous_mean_bpm_mean   : number;
    previous_mean_bpm_std    : number;
    previous_mean_bpm_variance: number;
    previous_mean_bpm_min : number;
    previous_mean_bpm_max   : number;  
    prev_time                : number;
    prev_max_bpm             : number;
    prev_min_bpm             : number;
    prev_mean_bpm            : number;
    humidity                : number;
    pressure                : number;
    clouds                   : number;
    wind_speed               : number;
    temperature             : number;
    temperature_feels_like  : number;
    co                       : number;
    o3 :number;
    no2                     : number;
    pm10                    : number;
    pm2_5                    : number;
    so2                      : number;
    fatigue_before           : number;
    fatigue_after            : number;
    charge_before        : number;
}